# Teste API

GET http://localhost:3003/ping

###
# Cria Nova Turma

POST http://localhost:3003/team
Content-Type: application/json

{
  "nome": "Turma SW"
}

###
# Buscar turmas ativas

GET http://localhost:3003/team
